auto_scale_lr = dict(base_batch_size=256)
backend_args = dict(backend='local')
base_lr = 0.004
codec = dict(
    input_size=(
        256,
        256,
    ),
    normalize=False,
    sigma=(
        5.66,
        5.66,
    ),
    simcc_split_ratio=2.0,
    type='SimCCLabel',
    use_dark=False)
custom_hooks = [
    dict(
        ema_type='ExpMomentumEMA',
        momentum=0.0002,
        priority=49,
        type='EMAHook',
        update_buffers=True),
    dict(
        switch_epoch=200,
        switch_pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(
                rotate_factor=180,
                scale_factor=[
                    0.75,
                    1.25,
                ],
                shift_factor=0.0,
                type='RandomBBoxTransform'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.2, type='Blur'),
                    dict(p=0.2, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=0.5,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        256,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        5.66,
                        5.66,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='mmdet.PipelineSwitchHook'),
]
data_mode = 'topdown'
data_root = 'data/'
dataset_coco = dict(
    ann_file='coco/annotations/coco_wholebody_train_v1.0.json',
    data_mode='topdown',
    data_prefix=dict(img='detection/coco/train2017/'),
    data_root='data/',
    pipeline=[],
    type='CocoWholeBodyHandDataset')
dataset_freihand = dict(
    ann_file='freihand/annotations/freihand_train.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/FreiHand/'),
    data_root='data/',
    pipeline=[],
    type='FreiHandDataset')
dataset_halpehand = dict(
    ann_file='halpe/annotations/halpe_train_v1.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/Halpe/hico_20160224_det/images/train2015/'),
    data_root='data/',
    pipeline=[],
    type='HalpeHandDataset')
dataset_onehand10k = dict(
    ann_file='onehand10k/annotations/onehand10k_train.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/OneHand10K/'),
    data_root='data/',
    pipeline=[],
    type='OneHand10KDataset')
dataset_rhd = dict(
    ann_file='rhd/annotations/rhd_train.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/RHD/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    1,
                    4,
                ),
                (
                    2,
                    3,
                ),
                (
                    3,
                    2,
                ),
                (
                    4,
                    1,
                ),
                (
                    5,
                    8,
                ),
                (
                    6,
                    7,
                ),
                (
                    7,
                    6,
                ),
                (
                    8,
                    5,
                ),
                (
                    9,
                    12,
                ),
                (
                    10,
                    11,
                ),
                (
                    11,
                    10,
                ),
                (
                    12,
                    9,
                ),
                (
                    13,
                    16,
                ),
                (
                    14,
                    15,
                ),
                (
                    15,
                    14,
                ),
                (
                    16,
                    13,
                ),
                (
                    17,
                    20,
                ),
                (
                    18,
                    19,
                ),
                (
                    19,
                    18,
                ),
                (
                    20,
                    17,
                ),
            ],
            num_keypoints=21,
            type='KeypointConverter'),
    ],
    type='Rhd2DDataset')
dataset_type = 'CocoWholeBodyHandDataset'
default_hooks = dict(
    badcase=dict(
        badcase_thr=5,
        enable=False,
        metric_type='loss',
        out_dir='badcase',
        type='BadCaseAnalysisHook'),
    checkpoint=dict(
        interval=10,
        max_keep_ckpts=1,
        rule='greater',
        save_best='AUC',
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(enable=False, type='PoseVisualizationHook'))
default_scope = 'mmpose'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
load_from = None
log_level = 'INFO'
log_processor = dict(
    by_epoch=True, num_digits=6, type='LogProcessor', window_size=50)
max_epochs = 210
model = dict(
    backbone=dict(
        _scope_='mmdet',
        act_cfg=dict(type='SiLU'),
        arch='P5',
        channel_attention=True,
        deepen_factor=0.67,
        expand_ratio=0.5,
        init_cfg=dict(
            checkpoint=
            'https://download.openmmlab.com/mmpose/v1/projects/rtmpose/cspnext-m_udp-aic-coco_210e-256x192-f2f7d6f6_20230130.pth',
            prefix='backbone.',
            type='Pretrained'),
        norm_cfg=dict(type='SyncBN'),
        out_indices=(4, ),
        type='CSPNeXt',
        widen_factor=0.75),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='PoseDataPreprocessor'),
    head=dict(
        decoder=dict(
            input_size=(
                256,
                256,
            ),
            normalize=False,
            sigma=(
                5.66,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        final_layer_kernel_size=7,
        gau_cfg=dict(
            act_fn='SiLU',
            drop_path=0.0,
            dropout_rate=0.0,
            expansion_factor=2,
            hidden_dims=256,
            pos_enc=False,
            s=128,
            use_rel_bias=False),
        in_channels=768,
        in_featuremap_size=(
            8,
            8,
        ),
        input_size=(
            256,
            256,
        ),
        loss=dict(
            beta=10.0,
            label_softmax=True,
            type='KLDiscretLoss',
            use_target_weight=True),
        out_channels=21,
        simcc_split_ratio=2.0,
        type='RTMCCHead'),
    test_cfg=dict(flip_test=True),
    type='TopdownPoseEstimator')
optim_wrapper = dict(
    optimizer=dict(lr=0.004, type='AdamW', weight_decay=0.05),
    paramwise_cfg=dict(
        bias_decay_mult=0, bypass_duplicate=True, norm_decay_mult=0),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1000, start_factor=1e-05,
        type='LinearLR'),
    dict(
        T_max=105,
        begin=105,
        by_epoch=True,
        convert_to_iter_based=True,
        end=210,
        eta_min=0.0002,
        type='CosineAnnealingLR'),
]
randomness = dict(seed=21)
resume = False
stage2_num_epochs = 10
test_cfg = dict()
test_dataloader = dict(
    batch_size=32,
    dataset=dict(
        datasets=[
            dict(
                ann_file='coco/annotations/coco_wholebody_val_v1.0.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/val2017/'),
                data_root='data/',
                pipeline=[],
                type='CocoWholeBodyHandDataset'),
            dict(
                ann_file='onehand10k/annotations/onehand10k_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/OneHand10K/'),
                data_root='data/',
                pipeline=[],
                type='OneHand10KDataset'),
            dict(
                ann_file='freihand/annotations/freihand_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/FreiHand/'),
                data_root='data/',
                pipeline=[],
                type='FreiHandDataset'),
            dict(
                ann_file='rhd/annotations/rhd_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/RHD/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                1,
                                4,
                            ),
                            (
                                2,
                                3,
                            ),
                            (
                                3,
                                2,
                            ),
                            (
                                4,
                                1,
                            ),
                            (
                                5,
                                8,
                            ),
                            (
                                6,
                                7,
                            ),
                            (
                                7,
                                6,
                            ),
                            (
                                8,
                                5,
                            ),
                            (
                                9,
                                12,
                            ),
                            (
                                10,
                                11,
                            ),
                            (
                                11,
                                10,
                            ),
                            (
                                12,
                                9,
                            ),
                            (
                                13,
                                16,
                            ),
                            (
                                14,
                                15,
                            ),
                            (
                                15,
                                14,
                            ),
                            (
                                16,
                                13,
                            ),
                            (
                                17,
                                20,
                            ),
                            (
                                18,
                                19,
                            ),
                            (
                                19,
                                18,
                            ),
                            (
                                20,
                                17,
                            ),
                        ],
                        num_keypoints=21,
                        type='KeypointConverter'),
                ],
                type='Rhd2DDataset'),
            dict(
                ann_file='halpe/annotations/halpe_val_v1.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/val2017/'),
                data_root='data/',
                pipeline=[],
                type='HalpeHandDataset'),
        ],
        metainfo=dict(
            from_file='configs/_base_/datasets/coco_wholebody_hand.py'),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CombinedDataset'),
    drop_last=False,
    num_workers=10,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
test_evaluator = [
    dict(thr=0.2, type='PCKAccuracy'),
    dict(type='AUC'),
    dict(type='EPE'),
]
train_cfg = dict(by_epoch=True, max_epochs=210, val_interval=10)
train_dataloader = dict(
    batch_size=256,
    dataset=dict(
        datasets=[
            dict(
                ann_file='coco/annotations/coco_wholebody_train_v1.0.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/train2017/'),
                data_root='data/',
                pipeline=[],
                type='CocoWholeBodyHandDataset'),
            dict(
                ann_file='onehand10k/annotations/onehand10k_train.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/OneHand10K/'),
                data_root='data/',
                pipeline=[],
                type='OneHand10KDataset'),
            dict(
                ann_file='freihand/annotations/freihand_train.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/FreiHand/'),
                data_root='data/',
                pipeline=[],
                type='FreiHandDataset'),
            dict(
                ann_file='rhd/annotations/rhd_train.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/RHD/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                1,
                                4,
                            ),
                            (
                                2,
                                3,
                            ),
                            (
                                3,
                                2,
                            ),
                            (
                                4,
                                1,
                            ),
                            (
                                5,
                                8,
                            ),
                            (
                                6,
                                7,
                            ),
                            (
                                7,
                                6,
                            ),
                            (
                                8,
                                5,
                            ),
                            (
                                9,
                                12,
                            ),
                            (
                                10,
                                11,
                            ),
                            (
                                11,
                                10,
                            ),
                            (
                                12,
                                9,
                            ),
                            (
                                13,
                                16,
                            ),
                            (
                                14,
                                15,
                            ),
                            (
                                15,
                                14,
                            ),
                            (
                                16,
                                13,
                            ),
                            (
                                17,
                                20,
                            ),
                            (
                                18,
                                19,
                            ),
                            (
                                19,
                                18,
                            ),
                            (
                                20,
                                17,
                            ),
                        ],
                        num_keypoints=21,
                        type='KeypointConverter'),
                ],
                type='Rhd2DDataset'),
            dict(
                ann_file='halpe/annotations/halpe_train_v1.json',
                data_mode='topdown',
                data_prefix=dict(
                    img='pose/Halpe/hico_20160224_det/images/train2015/'),
                data_root='data/',
                pipeline=[],
                type='HalpeHandDataset'),
        ],
        metainfo=dict(
            from_file='configs/_base_/datasets/coco_wholebody_hand.py'),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(
                rotate_factor=180,
                scale_factor=[
                    0.5,
                    1.5,
                ],
                type='RandomBBoxTransform'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.1, type='Blur'),
                    dict(p=0.1, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=1.0,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        256,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        5.66,
                        5.66,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=False,
        type='CombinedDataset'),
    num_workers=10,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(
        rotate_factor=180,
        scale_factor=[
            0.5,
            1.5,
        ],
        type='RandomBBoxTransform'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(input_size=(
        256,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.1, type='Blur'),
            dict(p=0.1, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=1.0,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                256,
                256,
            ),
            normalize=False,
            sigma=(
                5.66,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
train_pipeline_stage2 = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(
        rotate_factor=180,
        scale_factor=[
            0.75,
            1.25,
        ],
        shift_factor=0.0,
        type='RandomBBoxTransform'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(input_size=(
        256,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.2, type='Blur'),
            dict(p=0.2, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=0.5,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                256,
                256,
            ),
            normalize=False,
            sigma=(
                5.66,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
val_cfg = dict()
val_coco = dict(
    ann_file='coco/annotations/coco_wholebody_val_v1.0.json',
    data_mode='topdown',
    data_prefix=dict(img='detection/coco/val2017/'),
    data_root='data/',
    pipeline=[],
    type='CocoWholeBodyHandDataset')
val_dataloader = dict(
    batch_size=32,
    dataset=dict(
        datasets=[
            dict(
                ann_file='coco/annotations/coco_wholebody_val_v1.0.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/val2017/'),
                data_root='data/',
                pipeline=[],
                type='CocoWholeBodyHandDataset'),
            dict(
                ann_file='onehand10k/annotations/onehand10k_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/OneHand10K/'),
                data_root='data/',
                pipeline=[],
                type='OneHand10KDataset'),
            dict(
                ann_file='freihand/annotations/freihand_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/FreiHand/'),
                data_root='data/',
                pipeline=[],
                type='FreiHandDataset'),
            dict(
                ann_file='rhd/annotations/rhd_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/RHD/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                1,
                                4,
                            ),
                            (
                                2,
                                3,
                            ),
                            (
                                3,
                                2,
                            ),
                            (
                                4,
                                1,
                            ),
                            (
                                5,
                                8,
                            ),
                            (
                                6,
                                7,
                            ),
                            (
                                7,
                                6,
                            ),
                            (
                                8,
                                5,
                            ),
                            (
                                9,
                                12,
                            ),
                            (
                                10,
                                11,
                            ),
                            (
                                11,
                                10,
                            ),
                            (
                                12,
                                9,
                            ),
                            (
                                13,
                                16,
                            ),
                            (
                                14,
                                15,
                            ),
                            (
                                15,
                                14,
                            ),
                            (
                                16,
                                13,
                            ),
                            (
                                17,
                                20,
                            ),
                            (
                                18,
                                19,
                            ),
                            (
                                19,
                                18,
                            ),
                            (
                                20,
                                17,
                            ),
                        ],
                        num_keypoints=21,
                        type='KeypointConverter'),
                ],
                type='Rhd2DDataset'),
            dict(
                ann_file='halpe/annotations/halpe_val_v1.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/val2017/'),
                data_root='data/',
                pipeline=[],
                type='HalpeHandDataset'),
        ],
        metainfo=dict(
            from_file='configs/_base_/datasets/coco_wholebody_hand.py'),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CombinedDataset'),
    drop_last=False,
    num_workers=10,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
val_evaluator = [
    dict(thr=0.2, type='PCKAccuracy'),
    dict(type='AUC'),
    dict(type='EPE'),
]
val_freihand = dict(
    ann_file='freihand/annotations/freihand_test.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/FreiHand/'),
    data_root='data/',
    pipeline=[],
    type='FreiHandDataset')
val_halpehand = dict(
    ann_file='halpe/annotations/halpe_val_v1.json',
    data_mode='topdown',
    data_prefix=dict(img='detection/coco/val2017/'),
    data_root='data/',
    pipeline=[],
    type='HalpeHandDataset')
val_onehand10k = dict(
    ann_file='onehand10k/annotations/onehand10k_test.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/OneHand10K/'),
    data_root='data/',
    pipeline=[],
    type='OneHand10KDataset')
val_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(input_size=(
        256,
        256,
    ), type='TopdownAffine'),
    dict(type='PackPoseInputs'),
]
val_rhd = dict(
    ann_file='rhd/annotations/rhd_test.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/RHD/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    1,
                    4,
                ),
                (
                    2,
                    3,
                ),
                (
                    3,
                    2,
                ),
                (
                    4,
                    1,
                ),
                (
                    5,
                    8,
                ),
                (
                    6,
                    7,
                ),
                (
                    7,
                    6,
                ),
                (
                    8,
                    5,
                ),
                (
                    9,
                    12,
                ),
                (
                    10,
                    11,
                ),
                (
                    11,
                    10,
                ),
                (
                    12,
                    9,
                ),
                (
                    13,
                    16,
                ),
                (
                    14,
                    15,
                ),
                (
                    15,
                    14,
                ),
                (
                    16,
                    13,
                ),
                (
                    17,
                    20,
                ),
                (
                    18,
                    19,
                ),
                (
                    19,
                    18,
                ),
                (
                    20,
                    17,
                ),
            ],
            num_keypoints=21,
            type='KeypointConverter'),
    ],
    type='Rhd2DDataset')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
